from itertools import product
from pathlib import Path

import pytest
import yaml

from repoforge.apply import build_apply_plan
from repoforge.init_config import (
    build_init_config,
    dump_init_config,
    init_repository_config,
    resolve_project_selection,
)
from repoforge.renderer import SUPPORTED_PROFILES, SUPPORTED_TYPES, render_readme

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "templates"
STANDARDS = ROOT / "standards"


@pytest.mark.parametrize(
    ("project_type", "profile"),
    sorted(product(SUPPORTED_TYPES, SUPPORTED_PROFILES)),
)
def test_init_config_supports_every_readme_and_default_standards(project_type, profile):
    config = build_init_config(
        project_type,
        profile,
        project_name="InitSmoke",
        repository_url="https://github.com/example/init-smoke",
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )

    assert config["repoforge"] == {
        "config_version": 1,
        "project_type": project_type,
        "profile": profile,
    }
    assert config["project_name"] == "InitSmoke"
    assert config["repository_url"] == "https://github.com/example/init-smoke"

    rendered = render_readme(
        project_type,
        profile,
        config,
        template_root=TEMPLATES,
    )
    assert "InitSmoke" in rendered

    plan = build_apply_plan(
        project_type,
        profile,
        config,
        standards_policy="default",
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )
    assert plan[0].path.as_posix() == "README.md"
    assert len({item.path for item in plan}) == len(plan)


def test_init_dump_round_trips_as_yaml():
    config = build_init_config(
        "scientific-python",
        "standard",
        project_name="MySpatialPackage",
        repository_url="https://github.com/example/my-spatial-package",
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )
    dumped = dump_init_config(config)
    loaded = yaml.safe_load(dumped)

    assert dumped.startswith("# Generated by RepoForge.")
    assert loaded == config
    assert loaded["contributing"]["issue_url"].endswith("/issues")
    assert loaded["citation"]["repository_code"] == (
        "https://github.com/example/my-spatial-package"
    )


def test_init_uses_target_directory_name_when_name_is_omitted(tmp_path):
    target = tmp_path / "sample-project"
    target.mkdir()

    output = init_repository_config(
        target,
        "frontend-library",
        "minimal",
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )
    config = yaml.safe_load(output.read_text(encoding="utf-8"))

    assert output == target / "repoforge.yml"
    assert config["project_name"] == "sample-project"
    assert config["repoforge"]["project_type"] == "frontend-library"


def test_init_refuses_to_replace_existing_config_without_force(tmp_path):
    config_path = tmp_path / "repoforge.yml"
    config_path.write_text("existing: true\n", encoding="utf-8")

    with pytest.raises(FileExistsError, match="--force"):
        init_repository_config(
            tmp_path,
            "scientific-python",
            "minimal",
            template_root=TEMPLATES,
            standards_root=STANDARDS,
        )

    assert config_path.read_text(encoding="utf-8") == "existing: true\n"


def test_init_force_replaces_existing_config(tmp_path):
    config_path = tmp_path / "repoforge.yml"
    config_path.write_text("existing: true\n", encoding="utf-8")

    init_repository_config(
        tmp_path,
        "research-algorithm",
        "standard",
        project_name="MethodLab",
        force=True,
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )
    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert config["project_name"] == "MethodLab"
    assert config["repoforge"]["project_type"] == "research-algorithm"


def test_apply_selection_can_come_from_init_config():
    config = build_init_config(
        "web-application",
        "full",
        project_name="Portal",
        template_root=TEMPLATES,
        standards_root=STANDARDS,
    )
    assert resolve_project_selection(config) == ("web-application", "full")


def test_cli_selection_overrides_config_selection():
    config = {
        "repoforge": {
            "config_version": 1,
            "project_type": "web-application",
            "profile": "full",
        }
    }
    assert resolve_project_selection(
        config,
        "desktop-application",
        "minimal",
    ) == ("desktop-application", "minimal")
